name: Lexa Medical Laboratory Deployment
on:
    push:
        branches: [production]

jobs:
    deploy:
        runs-on: ubuntu-latest 

        steps:
            - name: Checkout Application Code
              uses: actions/checkout@v4